### ISSUE TITLE
suggestion: Sidebar examples with submenus

### ISSUE THREAD

**Issue by aaronhudon-pq** [atherosai/ui#13]
The sidebar templates are fantastic.

Suggestion: add some examples expanding/collapsing submenus:

[Dashboard]
[Payments]
[Analytics]

---
[Dashboard]
[Payments] (clicked/expanded)
   [Submenu1]
   [Submenu2]
   [Submenu3]

**Comment by AgentKaash** [comment]
@a7v8x , @aaronhudon-pq  i like to add these as it suggested earlier.

**Comment by Emerson727** [comment]
[Dashboard]

<?php
class SystemAdministrationDashboard extends [TPage](https://adiantiframework.com.br/api?index=classes/Adianti-Control-TPage)
{
    /**
     * Class constructor
     * Creates the page
     */
    function __construct()
    {
        [parent::__construct](https://adiantiframework.com.br/api?index=classes/Adianti-Control-TPage#method___construct)();
        
        try
        {
            $html = new [THtmlRenderer](https://adiantiframework.com.br/api?index=classes/Adianti-Widget-Template-THtmlRenderer)('app/resources/system_admin_dashboard.html');
            
            [TTransaction::open](https://adiantiframework.com.br/api?index=classes/Adianti-Database-TTransaction#method_open)('permission');
            $indicator1 = new [THtmlRenderer](https://adiantiframework.com.br/api?index=classes/Adianti-Widget-Template-THtmlRenderer)('app/resources/info-box.html');
            $indicator2 = new [THtmlRenderer](https://adiantiframework.com.br/api?index=classes/Adianti-Widget-Template-THtmlRenderer)('app/resources/info-box.html');
            $indicator3 = new [THtmlRenderer](https://adiantiframework.com.br/api?index=classes/Adianti-Widget-Template-THtmlRenderer)('app/resources/info-box.html');
            $indicator4 = new [THtmlRenderer](https://adiantiframework.com.br/api?index=classes/Adianti-Widget-Template-THtmlRenderer)('app/resources/info-box.html');

**Comment by Emerson727** [comment]
<?php
class SystemAdministrationDashboard extends [TPage](https://adiantiframework.com.br/api?index=classes/Adianti-Control-TPage)
{
    /**
     * Class constructor
     * Creates the page
     */
    function __construct()
    {
        [parent::__construct](https://adiantiframework.com.br/api?index=classes/Adianti-Control-TPage#method___construct)();
        
        try
        {
            $html = new [THtmlRenderer](https://adiantiframework.com.br/api?index=classes/Adianti-Widget-Template-THtmlRenderer)('app/resources/system_admin_dashboard.html');
            
            [TTransaction::open](https://adiantiframework.com.br/api?index=classes/Adianti-Database-TTransaction#method_open)('permission');
            $indicator1 = new [THtmlRenderer](https://adiantiframework.com.br/api?index=classes/Adianti-Widget-Template-THtmlRenderer)('app/resources/info-box.html');
            $indicator2 = new [THtmlRenderer](https://adiantiframework.com.br/api?index=classes/Adianti-Widget-Template-THtmlRenderer)('app/resources/info-box.html');
            $indicator3 = new [THtmlRenderer](https://adiantiframework.com.br/api?index=classes/Adianti-Widget-Template-THtmlRenderer)('app/resources/info-box.html');
            $indicator4 = new [THtmlRenderer](https://adiantiframework.com.br/api?index=classes/Adianti-Widget-Template-THtmlRenderer)('app/resources/info-box.html');

**Comment by smk1993** [comment]
I am trying to contribute , but unable to run in local `npm run dev` is not working , can anyone help please

**Comment by prajeshElEvEn** [comment]
> I am trying to contribute , but unable to run in local `npm run dev` is not working , can anyone help please

You're not able to run `npm run dev`, because there is no such command available in `package.json` file.

If you'd take a look at the contents of `package.json` file, you can find, under the `scripts` attribute, there is no such command as `dev`.
```json title="package.json"
{
  ...
  "scripts": {
    "deploy": "npm run compress:imgs && npm run build && rm -rf node_modules react-examples/node_modules",
    "build": "npm run build:react-examples && node index.mjs",
    "build:react-examples": "cd react-examples && npm i && npm run build",
    "compress:imgs": "npx compress-images-with-sharp 80 ./ original"
  },
  ...
}
```
The `next.js` code is available inside `react-examples` directory. Here you can run `npm i` and then `npm run dev`. However, when you'll visit [http://localhost:3000](http://localhost:3000), you'll see `page not found` error. This is because, in this particular repository, the author is building `next.js` code and then using the static html files in order to display the components.

So, in order to run the code.
1. Install dependencies
```bash
npm i
```
2. Build the code
```bash
npm run build
```
3. Open `index.html` in a browser.
Alternatively, you can use `Live Server` extension in `vs-code` in order to run your code.

**Comment by prajeshElEvEn** [comment]
> this is how it looks!! Please help
> 
> ![Screenshot 2024-04-24 204756](https://private-user-images.githubusercontent.com/127012754/325273374-f7474137-bfcb-4603-bc4d-3c21dfbdc5ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5NzI5ODMsIm5iZiI6MTcxMzk3MjY4MywicGF0aCI6Ii8xMjcwMTI3NTQvMzI1MjczMzc0LWY3NDc0MTM3LWJmY2ItNDYwMy1iYzRkLTNjMjFkZmJkYzViYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNFQxNTMxMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNDlkZDI5OTcxMzNiZWI4ZTI5ODc0NjBlZTIyYmNjOTg2ZjcyMTNjYTcwZjQ4ZGY2Mzg4YjdhNTkwNDBmYzgxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-PX4ZuK2lV_C4RUG_cGuf5SduyiUjjse4Gj_sU_VabY)

Yes, that correct. What do you need help with?

**Comment by a7v8x** [comment]
Thanks, everyone the sidebar with submenus has been added here https://github.com/atherosai/ui/tree/main/sidebar-10
