### ISSUE TITLE
Uu

### ISSUE THREAD

**Issue by Maricarmenpl** [atherosai/ui#24]
https://github.com/atherosai/ui/blob/ca2e131cdb516e9a851421c5de7298614aaec461/footer-03/assets/instagram.svg#L1(https://www.instagram.com/oscarpulido149?igsh=MTFwMnUyOWRtOXcxaw==)

**Comment by Maricarmenpl** [comment]
> https://github.com/atherosai/ui/blob/ca2e131cdb516e9a851421c5de7298614aaec461/footer-03/assets/instagram.svg#L1(https://www.instagram.com/oscarpulido149?igsh=MTFwMnUyOWRtOXcxaw==)

**Comment by a7v8x** [comment]
sorry i do not understand what this means
