### ISSUE TITLE
Suggestions : Readme Reformat

### ISSUE THREAD

**Issue by lebe24** [atherosai/ui#37]
hey @a7v8x awesome repo you have here. cool collection of web UI's I can use for my website. but the issue is running it locally and going through each directory to find a good UI to use. Suggestions is hosting the site on codesandbox and also reformating the readme to showcase  the UI component and a link to the code and live preview.

### Example 

| Name                | Screenshot                                                                                                                                                                | Live URL                                                                                                      |          |                                                                                                     |
| ----------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------- | -------------------------------------------------------------------------------------------------------------- |
| name              | ![victoreke.com](https://github.com/Evavic44/portfolio-ideas/assets/62628408/97609b42-dd9f-42d9-af5c-b0a195e303f1)                                                        | [sample.com](https://sample.com)                                                                        |                                                                         |

**Comment by XinBaoCode** [comment]
Sure, why not give it a try by integrating `Vercel` deployment? If you're open to it, I'd be more than happy to develop this feature and submit a Pull Request for you.

**Comment by lebe24** [comment]
awesome we can work on this if you up for a collabo
