### ISSUE TITLE
 localhost:3000 404 This page could not be found.

### ISSUE THREAD

**Issue by baobooooo** [atherosai/ui#46]
I excute the readme example successfully, but the localhost:3000 still can't be visited 
3000 port are  not in use, there are no firewall issues, and the backend runs smoothly.
But the website still shows that **"404 This page could not be found."**

**Comment by prajeshElEvEn** [comment]
> I excute the readme example successfully, but the localhost:3000 still can't be visited 
> 3000 port are  not in use, there are no firewall issues, and the backend runs smoothly.
> But the website still shows that **"404 This page could not be found."**
> 

You can take a look at [this](https://github.com/atherosai/ui/issues/13#issuecomment-1988467955). Here, I have explained how the code is executing and how you can run it.

**Comment by baobooooo** [comment]
you're right, now I understand. Thank you!
