### ISSUE TITLE
npm run dev is not working as intended

### ISSUE THREAD

**Issue by Ciezo** [atherosai/ui#55]
![image](https://github.com/atherosai/ui/assets/74012129/ef363a88-e110-43de-891c-9cbde27357f9)

**Comment by Ciezo** [comment]
After runing `npm run deploy` I got this error. May I kindly ask for assistance? I want to build this project into React.js components.

![image](https://github.com/atherosai/ui/assets/74012129/33971e94-6253-4a43-a67d-22a1e9d82410)

**Comment by Skelptin** [comment]
@Ciezo Hey you need to go into react-examples directory and then run those command

**Comment by Faisalansari203** [comment]
specify the dev  command in scripts present in package.json  folder 

![Screenshot 2024-04-20 043323](https://github.com/atherosai/ui/assets/113772320/ec7d155a-7695-4aaf-bd72-8eacd67f1b7c)

**Comment by Ciezo** [comment]
Ohhh...😅 Thank youuuu so much!

**Comment by Ciezo** [comment]
I still have some occurring problems. 

![image](https://github.com/atherosai/ui/assets/74012129/1df478dc-3b78-418e-91ed-e8bba937c281)


As the attached image illustrates, after navigating to the `react-examples` directory I run the command npm run dev. However, there is an error...

**Comment by Ciezo** [comment]
I think the problem here is that for some reason I don't have the index.js ?

![image](https://github.com/atherosai/ui/assets/74012129/3fc7bd7d-7b92-46bc-acb3-80c8c718b4bf)

**Comment by Ciezo** [comment]
This issue has been solved with the help of @Armanxrza. We need to just navigate to the `react-examples` folder and run the scripts associated with the `package.json`. Or, we can simply open up the `index.html` with a live server.
