### ISSUE TITLE
[BUG] Responsiveness

### ISSUE THREAD

**Issue by Brijesh1963** [atherosai/ui#9]
Need to be proper responsiveness for galaxy fold devices.
go to "https://learning.atheros.ai/#homepageCards"
 
Footer section need to be proper repositioning
![Screenshot 2023-10-12 001652](https://github.com/atherosai/ui/assets/98037970/d018f06c-4a43-488d-83b0-157239a11433)

**Comment by a7v8x** [comment]
thanks for letting us know about this! We will fix this till the end of the week!
